version: '3'
services:
  front:
    build: ./front
    ports:
     - "8080:8080"
  back:
    build: ./api
    ports:
    - "8081:8081"
  db:
    image: mysql
    ports:
      - "8082:8082"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
