version: '3'
services:


  front:
    build: ./front
    ports:
     - "8080:8080"

  back:
    build: ./api
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - "8081:8081"

  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=tlc
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt


  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
